remove placeholder workflow, try new permissions checker

diff --git a/.github/workflows/permissions.yaml b/.github/workflows/permissions.yaml
--- a/.github/workflows/permissions.yaml
+++ b/.github/workflows/permissions.yaml
@@ -6,7 +6,18 @@ jobs:
   check:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions-cool/check-user-permission@main
-        id: checkUser
+      - id: auth_check
+        uses: morfien101/actions-authorized-user@v3
         with:
-          require: 'write'
+          username: ${{ github.actor }}
+          team: ""
+          org: ${{ github.repo_owner }}
+          whitelist: "renovate[bot]"
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: can continue
+        shell: bash
+        run: |
+          if [ ${{ steps.auth_check.outputs.authorized }} != "true" ]; then
+            echo "::error title=User Unauthorized::User ${{ github.actor }} is not authorized to run this workflow!"
+            exit 1
+          fi
